### PR TITLE
Feature/table column toggle

### PR DESCRIPTION
**Pull request by pemeraldy**
1. Implemented the features that gives users ability to toggle the visibility of  the columns on a log table.

### CODE REVIEW

**Comment by pemeraldy** [comment]
@BFergerson, you can review this update.

**Comment by BFergerson** [comment]
Adding and removing columns works but what's the need for this section:
image

**Comment by pemeraldy** [comment]
> Adding and removing columns works but what's the need for this section: image

Hmmm... It's actually how element-ui multiselect works by default I think. 
I will remove it now.

**Comment by pemeraldy** [comment]
@BFergerson I have removed the tags.

**Comment by BFergerson** [comment]
@pemeraldy, when you're ready for review you should mark your PR as ready for review.

Either way, I checked this out and when I disable all the columns and re-enable one column, two columns get enabled:

two-columns
> I only clicked contentType and contentType + content became visible.

**Comment by BFergerson** [comment]
Couple issues:

#### Also, by default I just want the Service, Instance, and Content columns to be shown when ?portal=true
> This no longer works

#### Clicking next to the +/- buttons still causes the same issue as before
Peek 2022-06-02 16-36

---

Please fully test your fixes. After you fix please include a screencast showing it working correctly.

**Comment by pemeraldy** [comment]
@BFergerson 
main-view
This shows the main view.

The view when `portal=true`
portal-view

**Comment by pemeraldy** [comment]
> @pemeraldy, this still doesn't seem to be a good user experience: flash [ ](https://user-images.githubusercontent.com/3278877/171858209-fdc7698a-8b59-4c89-ae34-62fe84b88256.gif) flash [ ](https://user-images.githubusercontent.com/3278877/171858209-fdc7698a-8b59-4c89-ae34-62fe84b88256.gif)
> 
> I think you should re-implement this functionality using a popover with checkboxes or something equivalent. Let me know what you think would work.

I think a dropdown with the names of columns will do just fine.
When a column is clicked, it should have an active state, and look normal when it's not shown on the table.

**Comment by pemeraldy** [comment]
> >           ](https://user-images.githubusercontent.com/3278877/171858209-fdc7698a-8b59-4c89-ae34-62fe84b88256.gif)
> >         
> >        [ ](https://user-images.githubusercontent.com/3278877/171858209-fdc7698a-8b59-4c89-ae34-62fe84b88256.gif)
> > I think you should re-implement this functionality using a popover with checkboxes or something equivalent. Let me know what you think would work.
> 
> I think a dropdown with the names of columns will do just fine. When a column is clicked, it should have an active state, and look normal when it's not shown on the table.

**Comment by pemeraldy** [comment]
@BFergerson , Please take a look at the updates made

**Comment by pemeraldy** [comment]
fullView
Normal View.

portalView
Portal view

**Comment by BFergerson** [comment]
@pemeraldy, two issues:
1. Show all doesn't work if you unselect just one checkbox. (This issue is visible in your screencast above)
2. There is an extra row between the divider and service checkbox. (This issue is visible in your screencast above)

**Comment by pemeraldy** [comment]
>Show all doesn't work if you unselect just one checkbox. (This issue is visible in your screencast above)

I am not sure, but I will take a look at it.

**Comment by BFergerson** [comment]
@pemeraldy, look at your gif:


Notice you click  "Show All" and nothing happens.

**Comment by pemeraldy** [comment]
@BFergerson,  The issues pointed out has been fixed.

**Comment by BFergerson** [comment]
1. Each menu item has an unclickable area around it (probably padding)
2. I think you're missing the `@element-plus/icons-vue` dependency (i.e. package.json changes not committed)
3. Clean up commented code

**Comment by pemeraldy** [comment]
>Each menu item has an unclickable area around it (probably padding)

I will check it out and tend to others

**Comment by pemeraldy** [comment]
@BFergerson 
image
The padding on each checkbox is by default added by element UI, So i've removed the padding on each checkbox, and decided to put it on the wrapper instead. 
Please let me know if this looks ok, Though I am not really ok with how the divider between the `hide all` and `services` checkbox is looking.

**Comment by BFergerson** [comment]
Yeah, please fix the spacing. It should look like it did before.

**Comment by pemeraldy** [comment]
@BFergerson 
Test-padding
Default View

Test-padding-portal
Portal View

**Comment by pemeraldy** [comment]
@BFergerson I tried resolving the existing conflict but seems I don't have access to the `jetbrain-ui` branch

**Comment by pemeraldy** [comment]
@BFergerson 
I can't seem to understand what is the cause of this conflict, I already pulled updates and tried a merge with `jetbrains-ui` branch locally and I had no conflict.

**Comment by pemeraldy** [comment]
So, I have been able to resolve the issue but all network calls fails

**Pull request merged**
