### PR TITLE
Sync main

### PR DESCRIPTION
**Pull request by pemeraldy**
1. A holistic conflict resolves mergin jetbrains-ui with main

### CODE REVIEW

**Comment by BFergerson** [comment]
There's extra space in the portal view:
image

Traces get cut off:
image

**Comment by pemeraldy** [comment]
Ok, on it.

**Comment by pemeraldy** [comment]
@BFergerson  all ui bugs fixed

**Comment by BFergerson** [comment]
@pemeraldy, same issue is still present on logs:
Peek 2022-07-17 12-04

**Comment by pemeraldy** [comment]
> @pemeraldy, same issue is still present on logs: Peek 2022-07-17 12-04 [ Peek 2022-07-17 12-04 ](https://user-images.githubusercontent.com/3278877/179389559-92dbd4d8-1051-4ee6-9b39-e0e202b2b5a3.gif) [ ](https://user-images.githubusercontent.com/3278877/179389559-92dbd4d8-1051-4ee6-9b39-e0e202b2b5a3.gif)

Wow! I did test log out too... 
On it now.

**Comment by pemeraldy** [comment]
@BFergerson  Log overflow fixed. It was caused by the log Header component I already moved into the [tools component](https://github.com/sourceplusplus/skywalking-booster-ui/blob/a8edbf33e468e199eb66948c1691cffef4cec3a8/src/views/dashboard/panel/Tool.vue#L187) .

**Pull request merged**
